// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMev1MUEpTuqzmQ4XgZrTR7kDehAmOZq8',
    appId: '1:131880562602:web:a855945a90f012bd90c5d3',
    messagingSenderId: '131880562602',
    projectId: 'our-wallet-6e3f5',
    authDomain: 'our-wallet-6e3f5.firebaseapp.com',
    storageBucket: 'our-wallet-6e3f5.firebasestorage.app',
    measurementId: 'G-MH6L1CC5JK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoha5oE46IMHUaAqOanFScnetTBTJcHwo',
    appId: '1:131880562602:android:90f611ebd9df2b3b90c5d3',
    messagingSenderId: '131880562602',
    projectId: 'our-wallet-6e3f5',
    storageBucket: 'our-wallet-6e3f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBwEFyVkn8x8GgQg9p04SeEqaNqKl-UvA',
    appId: '1:131880562602:ios:26b5d8099801ca9490c5d3',
    messagingSenderId: '131880562602',
    projectId: 'our-wallet-6e3f5',
    storageBucket: 'our-wallet-6e3f5.firebasestorage.app',
    iosBundleId: 'com.example.smartWedding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBwEFyVkn8x8GgQg9p04SeEqaNqKl-UvA',
    appId: '1:131880562602:ios:26b5d8099801ca9490c5d3',
    messagingSenderId: '131880562602',
    projectId: 'our-wallet-6e3f5',
    storageBucket: 'our-wallet-6e3f5.firebasestorage.app',
    iosBundleId: 'com.example.smartWedding',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMev1MUEpTuqzmQ4XgZrTR7kDehAmOZq8',
    appId: '1:131880562602:web:df2cb79dcb61099790c5d3',
    messagingSenderId: '131880562602',
    projectId: 'our-wallet-6e3f5',
    authDomain: 'our-wallet-6e3f5.firebaseapp.com',
    storageBucket: 'our-wallet-6e3f5.firebasestorage.app',
    measurementId: 'G-ZYGCDBN0E5',
  );
}
